export const ADDED_TRACK = 'ADDED_TRACK';
export const REMOVED_SONG = 'REMOVED_SONG';

export const LOAD_QUEUE_REQUEST = 'LOAD_QUEUE_REQUEST';
export const LOAD_QUEUE_SUCCESS = 'LOAD_QUEUE_SUCCESS';
export const LOAD_QUEUE_FAILURE = 'LOAD_QUEUE_FAILURE';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const FETCH_TOKEN_REQUEST = 'FETCH_TOKEN_REQUEST';
export const FETCH_TOKEN_SUCCESS = 'FETCH_TOKEN_SUCCESS';
export const FETCH_TOKEN_FAILURE = 'FETCH_TOKEN_FAILURE';

export const LOAD_DEVICE_REQUEST = 'LOAD_DEVICE_REQUEST';
export const LOAD_DEVICE_SUCCESS = 'LOAD_DEVICE_SUCCESS';
export const LOAD_DEVICE_FAILURE = 'LOAD_DEVICE_FAILURE';

export const DELETE_TRACK_REQUEST = 'DELETE_TRACK_REQUEST';
export const DELETE_TRACK_SUCCESS = 'DELETE_TRACK_SUCCESS';
export const DELETE_TRACK_FAILURE = 'DELETE_TRACK_FAILURE';

export const SET_TRACK_STATE = 'SET_TRACK_STATE';

export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';
export const SET_CURRENT_DEVICE = 'SET_CURRENT_DEVICE';
